#!/bin/sh
set -eu

: "${MYSQL_MIGRATION_USER:?MYSQL_MIGRATION_USER is required}"
: "${MYSQL_MIGRATION_PASSWORD:?MYSQL_MIGRATION_PASSWORD is required}"
: "${MYSQL_QUERY_USER:?MYSQL_QUERY_USER is required}"
: "${MYSQL_QUERY_PASSWORD:?MYSQL_QUERY_PASSWORD is required}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${MYSQL_MIGRATION_USER}'@'%' IDENTIFIED BY '${MYSQL_MIGRATION_PASSWORD}';
CREATE USER IF NOT EXISTS '${MYSQL_QUERY_USER}'@'%' IDENTIFIED BY '${MYSQL_QUERY_PASSWORD}';
GRANT ALL PRIVILEGES ON foreign_trade_db.* TO '${MYSQL_MIGRATION_USER}'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${MYSQL_QUERY_USER}'@'%';
GRANT SELECT ON foreign_trade_db.* TO '${MYSQL_QUERY_USER}'@'%';
FLUSH PRIVILEGES;
SQL
